framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
            query.bus:
        transports:
            sync: 'sync://'
        routing:
            'App\Shared\Application\Query\QueryInterface': sync
            'App\Shared\Application\Command\CommandInterface': sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
