parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Shared\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Assistance\Domain\CountryPolicy\CountryTaxResidencyPolicyInterface:
            tags: ['app.assistance.country.tax.residency.policy']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Assistance/Infrastructure/Ui/Http/Resource/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Shared/Infrastructure/Symfony/Kernel.php'

    App\Assistance\Infrastructure\Registry\CountryTaxResidencyPoliciesRegistry:
        arguments:
            - !tagged_locator { tag: 'app.assistance.country.tax.residency.policy', default_index_method: 'getCountryCode' }

    App\Assistance\Infrastructure\ApiPlatform\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
